[package]
name = "tungsten"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
glam = "0.30"
image = { version = "0.25.9", default-features = false, features = ["png"] }
meshopt = "0.6.2"
png = "0.18.1"
sdl3 = { version = "0.18.4", default-features = false, features = ["use-pkg-config"] }
serde = { version = "1.0", features = ["derive"] }
tobj = { version = "4.0.4", default-features = false }
toml = "0.9"
