# Runtime terrain rendering knobs.
#worldmap = "assets/worldmaps/continent/manifest.toml"
#worldmap = "assets/worldmaps/continent_32k/manifest.toml"
worldmap = "assets/worldmaps/continent_water/manifest.toml"

render_debug_visuals = true

start_x = 1900.0
start_y = 4460.0
start_height = 250.0

raster_cube_enabled = true
raster_cube_x = 1965.0
raster_cube_y = 4315.0
raster_cube_height = 230.0
raster_cube_size = 96.0

raster_model_enabled = false
raster_model_path = ""
raster_model_x = 320.0
raster_model_y = 240.0
raster_model_height = 120.0
raster_model_scale = 1.0
raster_model_yaw_degrees = 0.0

# [ Platladan ]
present_mode = "vsync"
max_framerate = 200.0
performance_render_scale = 0.5
tile_cache_radius = 2
ray_iteration_count = 100
near_dda_distance = 512.0
near_dda_max_steps = 1024
height_lod_blend_start = 250.0
height_lod_blend_end = 600.0
normal_detail_blend_start = 500.0
normal_detail_blend_end = 1000.0

# [ Dunderklumpen ]
# present_mode = "immediate"
# max_framerate = 200.0
# performance_render_scale = 0.33
# tile_cache_radius = 1
# ray_iteration_count = 250
# near_dda_distance = 32.0
# near_dda_max_steps = 128
# height_lod_blend_start = 200.0
# height_lod_blend_end = 328.0
# normal_detail_blend_start = 500.0
# normal_detail_blend_end = 1000.0
